# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to the main host configuration instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = {
        device = "/dev/mapper/luks-1997b811-0abe-4844-93b4-89bd47d90aef";
        fsType = "ext4";
    };

    boot.initrd.luks.devices."luks-1997b811-0abe-4844-93b4-89bd47d90aef".device = "/dev/disk/by-uuid/1997b811-0abe-4844-93b4-89bd47d90aef";

    fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/3CC3-A49D";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
    };

    swapDevices = [
        { device = "/dev/mapper/luks-da0ece32-498b-46d5-9685-53c7ce33a1b5"; }
    ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
