#!/usr/bin/env bash
set -euo pipefail
cd "$HOME/Projects/iplayed"

if [ -t 1 ]; then
    exec uv run python ./iplayed_cli/app.py
else
    exec alacritty --working-directory "$HOME/Projects/iplayed" -e uv run python ./iplayed_cli/app.py
fi